---
- include: storage-service-packages.yml  tags=archivematica-ss
- include: configure-storage-service.yml tags=archivematica-ss
- include: archivematica-packages.yml    tags=archivematica-am
- include: configure-archivematica.yml   tags=archivematica-am
- include: sampledata.yml                tags=archivematica-sampledata
